{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if (include "consul.createTlsConfigmap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-tls-configuration" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  tls.json: |-
    {{- if .Values.tls.configuration }}
    {
      "tls": {{- include "common.tplvalues.render" ( dict "value" .Values.tls.configuration "context" $ ) | nindent 4 }}
    }
    {{- else }}
    {
      "tls": {
        "defaults": {
          "ca_file": "/opt/bitnami/consul/certificates/ca.crt",
          "cert_file": "/opt/bitnami/consul/certificates/tls.crt",
          "key_file": "/opt/bitnami/consul/certificates/tls.key"
        }
      }
    }
    {{- end }}
{{- end }}
