# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  fips: "false"
  images: |
    - name: alertmanager
      version: 0.28.1
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/alertmanager:0.28.1-debian-12-r20
    - name: os-shell
      version: "12"
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/os-shell:12-debian-12-r53
    - name: prometheus
      version: 3.7.2
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/prometheus:3.7.2-debian-12-r0
    - name: thanos
      version: 0.39.2
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/thanos:0.39.2-debian-12-r6
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 3.7.2
dependencies:
- name: common
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  tags:
  - bitnami-common
  version: 2.x.x
description: Prometheus is an open source monitoring and alerting system. It enables
  sysadmins to monitor their infrastructures by collecting metrics from configured
  targets at given intervals.
home: https://github.com/prometheus/prometheus
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/prometheus/img/prometheus-stack-220x234.png
keywords:
- prometheus
- monitoring
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: prometheus
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/prometheus
- https://github.com/bitnami/containers/tree/main/bitnami/prometheus
- https://github.com/prometheus/prometheus
- https://github.com/prometheus-community/helm-charts
version: 3.2.1
