# Copyright 2025 SolDevelo
# Based on Bitnami Common Helm Chart Â© Broadcom, Inc. (Apache-2.0)
# SPDX-License-Identifier: Apache-2.0

## soldevelo/common
## It is required by CI/CD tools and processes.
## @skip exampleValue
##
exampleValue: common-chart
