# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  fips: "false"
  images: |
    - name: grafana
      version: 12.2.1
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/grafana:12.2.1-debian-12-r0
    - name: os-shell
      version: "12"
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/os-shell:12-debian-12-r53
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 12.2.1
dependencies:
- name: common
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  tags:
  - bitnami-common
  version: 2.x.x
description: Grafana is an open source metric analytics and visualization suite for
  visualizing time series data that supports various types of data sources.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/grafana/img/grafana-stack-220x234.png
keywords:
- analytics
- monitoring
- metrics
- logs
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: grafana
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/grafana
version: 12.2.1
