# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  fips: "false"
  images: |
    - name: alertmanager
      version: 0.28.1
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/alertmanager:0.28.1-debian-12-r20
    - name: blackbox-exporter
      version: 0.27.0
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/blackbox-exporter:0.27.0-debian-12-r9
    - name: prometheus
      version: 3.7.2
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/prometheus:3.7.2-debian-12-r0
    - name: prometheus-operator
      version: 0.86.1
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/prometheus-operator:0.86.1-debian-12-r1
    - name: thanos
      version: 0.39.2
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/thanos:0.39.2-debian-12-r6
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 0.86.1
dependencies:
- condition: exporters.enabled,exporters.node-exporter.enabled
  name: node-exporter
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  version: 4.x.x
- condition: exporters.enabled,exporters.kube-state-metrics.enabled
  name: kube-state-metrics
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  version: 5.x.x
- name: common
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  tags:
  - bitnami-common
  version: 2.x.x
- name: kube-prometheus-crds
  repository: file://./charts/kube-prometheus-crds
  version: 0.x.x
description: Prometheus Operator provides easy monitoring definitions for Kubernetes
  services and deployment and management of Prometheus instances.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/prometheus-operator/img/prometheus-operator-stack-220x234.png
keywords:
- prometheus
- alertmanager
- operator
- monitoring
kubeVersion: '>= 1.16.0-0'
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: kube-prometheus
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/kube-prometheus
version: 11.4.0
