{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "temporal.worker.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" .) | nindent 4 }}
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: temporal
  {{- if or .Values.worker.deploymentAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.worker.deploymentAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" .) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.worker.autoscaling.hpa.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  {{- if .Values.worker.updateStrategy }}
  strategy: {{- toYaml .Values.worker.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.worker.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" (dict "customLabels" $podLabels "context" .) | nindent 6 }}
      app.kubernetes.io/component: worker
      app.kubernetes.io/part-of: temporal
  template:
    metadata:
      annotations:
      {{- if not .Values.existingConfigmap }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
      {{- if .Values.worker.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" .) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" (dict "customLabels" $podLabels "context" .) | nindent 8 }}
        app.kubernetes.io/component: worker
        app.kubernetes.io/part-of: temporal
        {{- if .Values.metrics.enabled }}
        temporal/metrics: "true"
        {{- end }}
    spec:
      {{- include "temporal.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ template "temporal.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.worker.automountServiceAccountToken }}
      {{- if .Values.worker.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.worker.hostAliases "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.worker.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.worker.affinity "context" .) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.worker.podAffinityPreset "component" "worker" "customLabels" $podLabels "context" .) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.worker.podAntiAffinityPreset "component" "worker" "customLabels" $podLabels "context" .) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.worker.nodeAffinityPreset.type "key" .Values.worker.nodeAffinityPreset.key "values" .Values.worker.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.worker.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.worker.nodeSelector "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.worker.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.worker.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.worker.priorityClassName }}
      priorityClassName: {{ .Values.worker.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.worker.schedulerName }}
      schedulerName: {{ .Values.worker.schedulerName | quote }}
      {{- end }}
      {{- if .Values.worker.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.worker.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.worker.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.worker.podSecurityContext "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.worker.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.worker.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        {{- include "temporal.defaultInitContainers.renderConfig" (dict "component" "worker" "context" .) | nindent 8 }}
      {{- if .Values.defaultInitContainers.waitForDB.enabled }}
        {{- include "temporal.defaultInitContainers.waitForDB" (dict "initialized" true "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.worker.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.worker.initContainers "context" .) | nindent 8 }}
      {{- end }}
      containers:
        - name: temporal-worker
          image: {{ template "temporal.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.worker.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.worker.containerSecurityContext "context" .) | nindent 12 }}
          {{- end }}
          command:
          {{- if .Values.diagnosticMode.enabled }}
            {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" .) | nindent 12 }}
          {{- else if .Values.worker.command }}
            {{- include "common.tplvalues.render" (dict "value" .Values.worker.command "context" .) | nindent 12 }}
          {{- end }}
          args:
          {{- if .Values.diagnosticMode.enabled }}
            {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" .) | nindent 12 }}
          {{- else if .Values.worker.args }}
            {{- include "common.tplvalues.render" (dict "value" .Values.worker.args "context" .) | nindent 12 }}
          {{- end }}
          env:
            - name: TEMPORAL_SERVICES
              value: worker
            {{- if include "common.fips.enabled" . }}
            - name: OPENSSL_FIPS
              value: {{ include "common.fips.config" (dict "tech" "openssl" "fips" .Values.worker.fips "global" .Values.global) | quote }}
            - name: GODEBUG
              value: {{ include "common.fips.config" (dict "tech" "golang" "fips" .Values.worker.fips "global" .Values.global) | quote }}
            {{- end }}
          {{- if .Values.worker.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.worker.extraEnvVars "context" .) | nindent 12 }}
          {{- end }}
          envFrom:
            {{- if .Values.worker.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.worker.extraEnvVarsCM "context" .) }}
            {{- end }}
            {{- if .Values.worker.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.worker.extraEnvVarsSecret "context" .) }}
            {{- end }}
          {{- if .Values.worker.resources }}
          resources: {{- toYaml .Values.worker.resources | nindent 12 }}
          {{- else if ne .Values.worker.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.worker.resourcesPreset) | nindent 12 }}
          {{- end }}
          ports:
            - name: membership
              containerPort: {{ .Values.worker.containerPorts.membership }}
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.worker.containerPorts.metrics }}
            {{- end }}
            {{- if .Values.worker.extraContainerPorts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.worker.extraContainerPorts "context" .) | nindent 12 }}
            {{- end }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.worker.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.worker.customLivenessProbe "context" .) | nindent 12 }}
          {{- else if .Values.worker.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.worker.livenessProbe "enabled") "context" .) | nindent 12 }}
            tcpSocket:
              port: membership
          {{- end }}
          {{- if .Values.worker.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.worker.customReadinessProbe "context" .) | nindent 12 }}
          {{- else if .Values.worker.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.worker.readinessProbe "enabled") "context" .) | nindent 12 }}
            tcpSocket:
              port: membership
          {{- end }}
          {{- if .Values.worker.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.worker.customStartupProbe "context" .) | nindent 12 }}
          {{- else if .Values.worker.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.worker.startupProbe "enabled") "context" .) | nindent 12 }}
            tcpSocket:
              port: membership
          {{- end }}
          {{- end }}
          {{- if .Values.worker.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.worker.lifecycleHooks "context" .) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/temporal/config/docker.yaml
              subPath: app-conf-dir/docker.yaml
            {{- if .Values.dynamicConfig }}
            - name: dynamic-config
              mountPath: /opt/bitnami/temporal/config/dynamicconfig/dynamic_config.yaml
              subPath: dynamic_config.yaml
            {{- end }}
            {{- if .Values.tls.enabled }}
            - name: tls-certs
              mountPath: /opt/bitnami/temporal/certs
              readOnly: true
            {{- end }}
          {{- if .Values.worker.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.worker.extraVolumeMounts "context" .) | nindent 12 }}
          {{- end }}
        {{- if .Values.worker.sidecars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.worker.sidecars "context" .) | nindent 8 }}
        {{- end }}
      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: configuration
          configMap:
            name: {{ template "temporal.configMapName" . }}
        {{- if .Values.usePasswordFiles }}
        - name: db-credentials
          projected:
            sources:
              - secret:
                  name: {{ include "temporal.database.default.secretName" . }}
                  items:
                    - key: {{ include "temporal.database.default.secretPasswordKey" . }}
                      path: default-store-password
              - secret:
                  name: {{ include "temporal.database.visibility.secretName" . }}
                  items:
                    - key: {{ include "temporal.database.visibility.secretPasswordKey" . }}
                      path: visibility-store-password
        {{- end }}
        {{- if .Values.tls.enabled }}
        - name: tls-certs
          projected:
            sources:
              {{- if (include "temporal.tls.ca.secretName" .) }}
              - secret:
                  name: {{ template "temporal.tls.ca.secretName" . }}
                  items:
                    - key: {{ .Values.tls.certCAFilename }}
                      path: ca.crt
              {{- end }}
              - secret:
                  name: {{ template "temporal.tls.internode.secretName" . }}
                  items:
                    - key: {{ ternary "tls.crt" .Values.tls.internode.certFilename .Values.tls.autoGenerated.enabled }}
                      path: internode.crt
                    - key: {{ ternary "tls.key" .Values.tls.internode.certKeyFilename .Values.tls.autoGenerated.enabled }}
                      path: internode.key
                    {{- if not (include "temporal.tls.ca.secretName" .) }}
                    - key: {{ ternary "ca.crt" .Values.tls.certCAFilename .Values.tls.autoGenerated.enabled }}
                      path: ca.crt
                    {{- end }}
              - secret:
                  name: {{ template "temporal.tls.frontend.secretName" . }}
                  items:
                    - key: {{ ternary "tls.crt" .Values.tls.frontend.certFilename .Values.tls.autoGenerated.enabled }}
                      path: frontend.crt
                    - key: {{ ternary "tls.key" .Values.tls.frontend.certKeyFilename .Values.tls.autoGenerated.enabled }}
                      path: frontend.key
        {{- end }}
        {{- if .Values.worker.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.worker.extraVolumes "context" .) | nindent 8 }}
        {{- end }}
