{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.sourceWatcher.enabled }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "flux.source-watcher.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- $versionLabel := dict "app.kubernetes.io/version" (include "common.images.version" (dict "imageRoot" .Values.sourceWatcher.image "chart" .Chart)) }}  
  {{- $labels := include "common.tplvalues.merge" (dict "values" (list $versionLabel .Values.commonLabels) "context" .) }}
  labels: {{- include "common.labels.standard" (dict "customLabels" $labels "context" .) | nindent 4 }}
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: source-watcher
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" .) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.sourceWatcher.updateStrategy }}
  strategy: {{- toYaml .Values.sourceWatcher.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list $versionLabel .Values.sourceWatcher.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" (dict "customLabels" $podLabels "context" .) | nindent 6 }}
      app.kubernetes.io/component: source-watcher
  template:
    metadata:
      {{- if .Values.sourceWatcher.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.podAnnotations "context" .) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" (dict "customLabels" $podLabels "context" .) | nindent 8 }}
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: source-watcher
    spec:
      serviceAccountName: {{ template "flux.source-watcher.serviceAccountName" . }}
      {{- include "flux.imagePullSecrets" . | nindent 6 }}
      automountServiceAccountToken: {{ .Values.sourceWatcher.automountServiceAccountToken }}
      {{- if .Values.sourceWatcher.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.hostAliases "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.sourceWatcher.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.affinity "context" .) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.sourceWatcher.podAffinityPreset "component" "source-watcher" "customLabels" $podLabels "context" .) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.sourceWatcher.podAntiAffinityPreset "component" "source-watcher" "customLabels" $podLabels "context" .) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.sourceWatcher.nodeAffinityPreset.type "key" .Values.sourceWatcher.nodeAffinityPreset.key "values" .Values.sourceWatcher.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.sourceWatcher.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.nodeSelector "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.sourceWatcher.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.sourceWatcher.priorityClassName }}
      priorityClassName: {{ .Values.sourceWatcher.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.sourceWatcher.schedulerName }}
      schedulerName: {{ .Values.sourceWatcher.schedulerName | quote }}
      {{- end }}
      {{- if .Values.sourceWatcher.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.sourceWatcher.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.sourceWatcher.podSecurityContext "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.sourceWatcher.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.sourceWatcher.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if or (and .Values.volumePermissions.enabled .Values.sourceWatcher.persistence.enabled) .Values.sourceWatcher.initContainers }}
      initContainers:
        {{- if and .Values.volumePermissions.enabled .Values.sourceWatcher.persistence.enabled }}
        - name: volume-permissions
          image: {{ include "flux.volumePermissions.image" . }}
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy | quote }}
          command:
            - /bin/bash
          args:
            - -ec
            - |
              mkdir -p {{ .Values.sourceWatcher.persistence.mountPath }}
              find {{ .Values.sourceWatcher.persistence.mountPath }} -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | xargs -r chown -R {{ .Values.sourceWatcher.containerSecurityContext.runAsUser }}:{{ .Values.sourceWatcher.podSecurityContext.fsGroup }}
          {{- if .Values.volumePermissions.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.volumePermissions.containerSecurityContext "context" .) | nindent 12 }}
          {{- end }}
          {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- else if ne .Values.volumePermissions.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.volumePermissions.resourcesPreset) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.sourceWatcher.persistence.mountPath }}
        {{- end }}
        {{- if .Values.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.initContainers "context" .) | nindent 8 }}
        {{- end }}
        {{- end }}
      containers:
        - name: source-watcher
          image: {{ template "flux.source-watcher.image" . }}
          imagePullPolicy: {{ .Values.sourceWatcher.image.pullPolicy }}
          {{- if .Values.sourceWatcher.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.sourceWatcher.containerSecurityContext "context" .) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" .) | nindent 12 }}
          {{- else if .Values.sourceWatcher.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.command "context" .) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" .) | nindent 12 }}
          {{- else if .Values.sourceWatcher.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.args "context" .) | nindent 12 }}
          {{- else }}
          args:
            - --watch-all-namespaces={{ .Values.watchAllNamespaces }}
            {{- if .Values.sourceWatcher.image.debug }}
            - --log-level=debug
            {{- else }}
            - --log-level=info
            {{- end }}
            - --log-encoding=json
            - --storage-addr=:{{ .Values.sourceWatcher.containerPorts.http }}
            - --metrics-addr=:{{ .Values.sourceWatcher.containerPorts.metrics }}
            - --health-addr=:{{ .Values.sourceWatcher.containerPorts.health }}
            - --storage-path={{ .Values.sourceWatcher.persistence.mountPath }}
            - --storage-adv-addr={{ template "flux.source-watcher.fullname" . }}.$(RUNTIME_NAMESPACE).svc.{{ .Values.clusterDomain }}
            - --enable-leader-election
           {{- if .Values.notificationController.enabled }}
            - --events-addr=http://{{ template "flux.notification-controller.fullname" . }}.$(RUNTIME_NAMESPACE).svc.{{ .Values.clusterDomain }}
            {{- end}}
          {{- end }}
          env:
            - name: RUNTIME_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TUF_ROOT
              value: "/tmp/.sigstore"
            {{- if .Values.sourceWatcher.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.extraEnvVars "context" .) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.sourceWatcher.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.extraEnvVarsCM "context" .) }}
            {{- end }}
            {{- if .Values.sourceWatcher.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.extraEnvVarsSecret "context" .) }}
            {{- end }}
          {{- if .Values.sourceWatcher.resources }}
          resources: {{- toYaml .Values.sourceWatcher.resources | nindent 12 }}
          {{- else if ne .Values.sourceWatcher.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.sourceWatcher.resourcesPreset) | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.sourceWatcher.containerPorts.http }}
            - name: http-metrics
              containerPort: {{ .Values.sourceWatcher.containerPorts.metrics }}
            - name: http-health
              containerPort: {{ .Values.sourceWatcher.containerPorts.health }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.sourceWatcher.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.customLivenessProbe "context" .) | nindent 12 }}
          {{- else if .Values.sourceWatcher.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.sourceWatcher.livenessProbe "enabled") "context" .) | nindent 12 }}
            httpGet:
              path: /healthz
              port: http-health
          {{- end }}
          {{- if .Values.sourceWatcher.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.customReadinessProbe "context" .) | nindent 12 }}
          {{- else if .Values.sourceWatcher.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.sourceWatcher.readinessProbe "enabled") "context" .) | nindent 12 }}
            httpGet:
              path: /readyz
              port: http-health
          {{- end }}
          {{- if .Values.sourceWatcher.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.customStartupProbe "context" .) | nindent 12 }}
          {{- else if .Values.sourceWatcher.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.sourceWatcher.startupProbe "enabled") "context" .) | nindent 12 }}
            httpGet:
              path: /healthz
              port: http-health
          {{- end }}
          {{- end }}
          {{- if .Values.sourceWatcher.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.lifecycleHooks "context" .) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.sourceWatcher.persistence.mountPath }}
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
          {{- if .Values.sourceWatcher.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.extraVolumeMounts "context" .) | nindent 12 }}
          {{- end }}
        {{- if .Values.sourceWatcher.sidecars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.sidecars "context" .) | nindent 8 }}
        {{- end }}
      volumes:
        - name: data
          {{- if .Values.sourceWatcher.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.persistence.existingClaim "context" .) | default (include "flux.source-watcher.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: empty-dir
          emptyDir: {}
        {{- if .Values.sourceWatcher.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.extraVolumes "context" .) | nindent 8 }}
        {{- end }}
{{- end }}
