{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.sourceWatcher.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "flux.source-watcher.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- $versionLabel := dict "app.kubernetes.io/version" (include "common.images.version" (dict "imageRoot" .Values.sourceWatcher.image "chart" .Chart)) }}  
  {{- $labels := include "common.tplvalues.merge" (dict "values" (list $versionLabel .Values.commonLabels) "context" .) }}
  labels: {{- include "common.labels.standard" (dict "customLabels" $labels "context" .) | nindent 4 }}
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: source-watcher
  {{- if or .Values.sourceWatcher.service.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.sourceWatcher.service.annotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" .) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.sourceWatcher.service.type }}
  {{- if and .Values.sourceWatcher.service.clusterIP (eq .Values.sourceWatcher.service.type "ClusterIP") }}
  clusterIP: {{ .Values.sourceWatcher.service.clusterIP }}
  {{- end }}
  {{- if .Values.sourceWatcher.service.sessionAffinity }}
  sessionAffinity: {{ .Values.sourceWatcher.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.sourceWatcher.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.service.sessionAffinityConfig "context" .) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.sourceWatcher.service.type "LoadBalancer") (eq .Values.sourceWatcher.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.sourceWatcher.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.sourceWatcher.service.type "LoadBalancer") (not (empty .Values.sourceWatcher.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.sourceWatcher.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.sourceWatcher.service.type "LoadBalancer") (not (empty .Values.sourceWatcher.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.sourceWatcher.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.sourceWatcher.service.ports.http }}
      protocol: TCP
      {{- if and (or (eq .Values.sourceWatcher.service.type "NodePort") (eq .Values.sourceWatcher.service.type "LoadBalancer")) (not (empty .Values.sourceWatcher.service.nodePorts.http)) }}
      nodePort: {{ .Values.sourceWatcher.service.nodePorts.http }}
      {{- else if eq .Values.sourceWatcher.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
      targetPort: http
    {{- if .Values.sourceWatcher.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.sourceWatcher.service.extraPorts "context" .) | nindent 4 }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.sourceWatcher.podLabels .Values.commonLabels) "context" .) }}
  selector: {{- include "common.labels.matchLabels" (dict "customLabels" $podLabels "context" .) | nindent 4 }}
    app.kubernetes.io/component: source-watcher
{{- end }}
